### PR TITLE
Resolved three issues

### LINKED ISSUE #14: Wrong link in the footer for About
In the footer of every page, the link for _About_ is _blog.html_

### LINKED ISSUE #19: All the links to third party site should open in a new tab
The one I have found till now is the link to the whatsapp group for SoI 2019

### LINKED ISSUE #26: Add link to github profile on index page

### PR DESCRIPTION
**Pull request by mrswagbhinav**
- Add link to github profile on index page (Closes #26 )
- All the links to third party site should open in a new tab (Closes #19 )
- Wrong link in the footer for About (Closes #14 )

### CODE REVIEW

**Comment by NeuralFlux** [comment]
Thanks for the PR, @mrswagbhinav ! I've updated your PR with the links to the issues they close, don't forget to do that next time! Also, I'll just review the changes and merge once done.

**Comment by NeuralFlux** [comment]
Hey @mrswagbhinav , I found one small bug about the external links on new tabs issue, they are 

- [SoI.html](https://github.com/mrswagbhinav/oss2019.github.io/blob/master/SoI.html)
- [hardware.html](https://github.com/mrswagbhinav/oss2019.github.io/blob/master/SoC19/hardware.html)

Can you add new tab to these too? Other than that this PR is perfect :smile:

**Comment by mrswagbhinav** [comment]
@NeuralFlux I fixed the links in [hardware.html ](https://github.com/mrswagbhinav/oss2019.github.io/blob/master/SoC19/hardware.html)and I think the only issue with [Sol.html ](https://github.com/mrswagbhinav/oss2019.github.io/blob/master/SoI.html)was the mailto link so I fixed that too.

**Comment by NeuralFlux** [comment]
Looks good to go, thank you @mrswagbhinav !

**Pull request merged**
