### PR TITLE
adjust screen size in mobile

### PR DESCRIPTION
**Pull request by AdityaSrivast**
Fixes: #36
Adjust webscreen size in mobile

### CODE REVIEW

**Comment by AdityaSrivast** [comment]
@sonusourav Please review

**Comment by sonusourav** [comment]
The SoI page looks fine to me but the home page banner and Github Flag still needs some improvement.

Screen Shot 2019-07-02 at 13 47 39
Screen Shot 2019-07-02 at 13 47 50

**Comment by AdityaSrivast** [comment]
@sonusourav what is the expected behaviour for both?

**Comment by sonusourav** [comment]
Something similar to what you achieved for SoI page or rather banner I would say.

## Before

WhatsApp Image 2019-07-02 at 3 58 46 PM

## After
Screen Shot 2019-07-02 at 15 57 41

**Comment by AdityaSrivast** [comment]
@sonusourav updated. Please review

**Comment by sonusourav** [comment]
Hey, the flag issue is still there. Could you please check that out as well?

**Comment by AdityaSrivast** [comment]
@sonusourav what's the expected behaviour of flag? I tried it shifting into view but it was blocking the content. Current position seems fine though

**Comment by sonusourav** [comment]
> 
> 
> @sonusourav what's the expected behavior of flag? I tried it shifting into view but it was blocking the content. Current position seems fine though

I think your point is valid for the flag. Shifting more would compromise with the details. Is there any possibility of betterment of home banner dimension?

**Comment by AdityaSrivast** [comment]
@sonusourav updated

**Comment by sonusourav** [comment]
Why is the "Open Student Society at the bottom? Could you bring the pic a bit in the middle of the screen when it loads and also the text?

**Comment by sonusourav** [comment]
The background image is fixed which should not be. Also, reduce the top space between the title and the home banner.

**Comment by AdityaSrivast** [comment]
> The background image is fixed which should not be. Also, reduce the top space between the title and the home banner.

@sonusourav we cannot achieve both the image at `center` and `un-fixed` simultaneously as the `background-position` is the property responsible for the parallax-effect.
There's an alternative however, to reduce the height of container, but still the image cannot be stretched to complete height and if not  certain spaces will be left to center the content vertically; OR we can go with increasing width of background, but it will be similar to the current scenario.
We cannot achieve everything simultaneously here.

**Comment by sonusourav** [comment]
I understand, let the parallax effect be there. We can compromise with the position of the text. But the picture should be in the middle when it loads for the first time.

**Comment by AdityaSrivast** [comment]
@sonusourav made the changes. Please review

**Comment by sonusourav** [comment]
Hey @AdityaSrivast everything looks fine to me. Just rebase the branch, your branch is behind the master branch. And once again, thank you for having so much patience.

**Comment by AdityaSrivast** [comment]
@sonusourav rebased the branch

**Pull request merged**
